#!/usr/bin/env bash
# garbage-collect.sh
#
# Recurring cleanup agent. Run on a schedule (e.g. weekly via CI cron).
# Scans for deviations from golden principles and opens targeted fix PRs.
#
# Usage:
#   ./scripts/garbage-collect.sh
#
# Requires: codex CLI, gh CLI, git

set -euo pipefail

MODEL="${CODEX_MODEL:-o4-mini}"
BRANCH="chore/agent-gc-$(date +%Y%m%d)"

echo "==> Starting garbage collection pass..."
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# ── Task 1: Update quality scores ──────────────────────────────────────────
echo "==> Updating quality scores..."
codex --model "$MODEL" \
  "Audit the codebase and update docs/QUALITY_SCORE.md with current grades for each domain.
   Grade each domain on: test coverage (run 'npm test -- --coverage' for data),
   type safety (count @ts-ignore and any usages), boundary validation (Zod usage at API calls),
   and E2E coverage (count Playwright specs per feature).
   Use the grading key already in that file. Update the 'Last updated' date.
   Do not change the file structure."

# ── Task 2: Find and flag missing Zod boundaries ───────────────────────────
echo "==> Checking for missing boundary validation..."
codex --model "$MODEL" \
  "Search src/lib/api/ and src/features/*/api.ts for fetch calls that use the result
   of res.json() without a Zod schema parse. For each one found, add a TODO comment:
   // TODO(gc): add Zod schema parse here — see docs/RELIABILITY.md
   and add an entry to docs/exec-plans/tech-debt-tracker.md with severity: medium,
   auto-fixable: false.
   Only add the TODO if it doesn't already exist on that line."

# ── Task 3: Find hand-rolled utilities that duplicate lib/ ──────────────────
echo "==> Checking for duplicated utilities..."
codex --model "$MODEL" \
  "Search src/features/ for utility functions (e.g. date formatting, string truncation,
   debounce implementations) that duplicate functionality already in src/lib/utils/.
   For each duplicate found, replace the hand-rolled version with an import from src/lib/utils/.
   If the shared utility doesn't exist yet, move the best implementation there first,
   then update all usages. Do not change behaviour."

# ── Task 4: Stale doc check ────────────────────────────────────────────────
echo "==> Checking for stale documentation..."
codex --model "$MODEL" \
  "Check docs/ for documentation that no longer reflects the actual codebase.
   Specifically: does ARCHITECTURE.md list all current feature domains under src/features/?
   Does docs/DESIGN.md list all components currently in src/lib/components/?
   Update any stale references. Do not invent new content — only fix inaccuracies."

# ── Commit and PR ──────────────────────────────────────────────────────────
if git diff --quiet && git diff --staged --quiet; then
  echo "==> No changes found. Codebase is clean."
  git checkout main
  git branch -d "$BRANCH"
  exit 0
fi

git add -A
git commit -m "chore: agent garbage collection $(date +%Y-%m-%d)"

echo "==> Opening PR..."
gh pr create \
  --title "chore: agent GC pass $(date +%Y-%m-%d)" \
  --body "Automated garbage collection pass. Changes:
- Updated quality scores in docs/QUALITY_SCORE.md
- Flagged missing Zod boundary validation
- Consolidated duplicated utility functions
- Updated stale documentation

These changes were generated by scripts/garbage-collect.sh.
Review is typically < 1 minute. Auto-merge if CI passes." \
  --base main \
  --label "agent-gc"

echo "==> Garbage collection PR opened."
